### ISSUE TITLE
拷贝代码后使用无效呢？

### ISSUE THREAD

**Issue by flyxinhua** [liranhao/rich_text_widget#1]
直接拷贝 rich_text_widget 跑起来是空的？

**Comment by liranhao** [comment]
是不是使用方式有问题？看下demo里的使用方式，我使用是正常的，或者直接pub引用， 这个已经发布到谷歌pub上了，可以查看
https://pub.dev/packages/rich_text_widget

**Comment by flyxinhua** [comment]
用了你的库，可以了。不过 defaultText  要设置 textstyle ，并设置颜色才能显示。我觉得可以默认黑色？

**Comment by liranhao** [comment]
> 用了你的库，可以了。不过 defaultText 要设置 textstyle ，并设置颜色才能显示。我觉得可以默认黑色？
这个可能是设置的Theme有关，我下个版本设置一下
